from PyGlow import PyGlow
from time import sleep

#b = 100
#s = 200

pyglow = PyGlow()
#pyglow = PyGlow(brightness=b, speed=s, pulse=True)

pyglow.all(0)

while True:
#	pyglow.led(1)
	pyglow.color("red",    100)
	pyglow.color("orange",   0)
	pyglow.color("yellow",   0)
	pyglow.color("green",    0)
	pyglow.color("blue",     0)
	pyglow.color("white",    0)
	sleep(0.1)
	pyglow.color("red",      0)
        pyglow.color("orange",   0)
        pyglow.color("yellow",   0)
        pyglow.color("green",    0)
        pyglow.color("blue",     0)
        pyglow.color("white",    0)
        sleep(0.1)
	pyglow.color("red",    100)
        pyglow.color("orange", 100)
        pyglow.color("yellow",   0)
        pyglow.color("green",    0)
        pyglow.color("blue",     0)
        pyglow.color("white",    0)
        sleep(0.1)
	pyglow.color("red",      0)
        pyglow.color("orange",   0)
        pyglow.color("yellow",   0)
        pyglow.color("green",    0)
        pyglow.color("blue",     0)
        pyglow.color("white",    0)
        sleep(0.1)
	pyglow.color("red",    100)
        pyglow.color("orange", 100)
        pyglow.color("yellow", 100)
        pyglow.color("green",    0)
        pyglow.color("blue",     0)
        pyglow.color("white",    0)
        sleep(0.1)
	pyglow.color("red",      0)
        pyglow.color("orange",   0)
        pyglow.color("yellow",   0)
        pyglow.color("green",    0)
        pyglow.color("blue",     0)
        pyglow.color("white",    0)
        sleep(0.1)
	pyglow.color("red",    100)
        pyglow.color("orange", 100)
        pyglow.color("yellow", 100)
        pyglow.color("green",  100)
        pyglow.color("blue",     0)
        pyglow.color("white",    0)
        sleep(0.1)
	pyglow.color("red",      0)
        pyglow.color("orange",   0)
        pyglow.color("yellow",   0)
        pyglow.color("green",    0)
        pyglow.color("blue",     0)
        pyglow.color("white",    0)
        sleep(0.1)
	pyglow.color("red",    100)
        pyglow.color("orange", 100)
        pyglow.color("yellow", 100)
        pyglow.color("green",  100)
        pyglow.color("blue",   100)
        pyglow.color("white",    0)
        sleep(0.1)
	pyglow.color("red",      0)
        pyglow.color("orange",   0)
        pyglow.color("yellow",   0)
        pyglow.color("green",    0)
        pyglow.color("blue",     0)
        pyglow.color("white",    0)
        sleep(0.1)
	pyglow.color("red",    100)
        pyglow.color("orange", 100)
        pyglow.color("yellow", 100)
        pyglow.color("green",  100)
        pyglow.color("blue",   100)
        pyglow.color("white",  100)
        sleep(0.1)
	pyglow.color("red",      0)
        pyglow.color("orange",   0)
        pyglow.color("yellow",   0)
        pyglow.color("green",    0)
        pyglow.color("blue",     0)
        pyglow.color("white",    0)
        sleep(0.1)

#	pyglow.all()
