from PyGlow import PyGlow
from time import sleep

pyglow = PyGlow()

pyglow.all(0)

count = 0
while (count < 5):
	pyglow.color("white", 60)
	sleep(0.1)
	pyglow.color("white", 	0)
	pyglow.color("blue",  100)
	sleep(0.1)
	pyglow.color("blue", 	0)
	pyglow.color("green", 100)
	sleep(0.1)
	pyglow.color("green", 	0)
	pyglow.color("yellow",100)
	sleep(0.1)
	pyglow.color("yellow",  0)
        pyglow.color("orange",100)
        sleep(0.1)
	pyglow.color("orange",  0)
        pyglow.color("red",   100)
        sleep(0.1)
	
	pyglow.color("white", 50)
	sleep(0.1)
	pyglow.color("white",   0)
	pyglow.color("blue",  100)
	sleep(0.1)
	pyglow.color("blue",    0)
        pyglow.color("green", 100)
        sleep(0.1)
	pyglow.color("green",   0)
        pyglow.color("yellow",100)
        sleep(0.1)
	pyglow.color("yellow",  0)
        pyglow.color("orange",100)
        sleep(0.1)
	
	pyglow.color("white",  40)
	sleep(0.1)
	pyglow.color("white",   0)
	pyglow.color("blue",  100)
	sleep(0.1)
	pyglow.color("blue",    0)
        pyglow.color("green", 100)
        sleep(0.1)
	pyglow.color("green",   0)
        pyglow.color("yellow",100)
        sleep(0.1)

	pyglow.color("white",  30)
        sleep(0.1) 
        pyglow.color("white",   0)
	pyglow.color("blue",  100)
	sleep(0.1)
	pyglow.color("blue",    0)
        pyglow.color("green", 100)
        sleep(0.1)
	
	pyglow.color("white",  20)
        sleep(0.1) 
        pyglow.color("white",   0)
	pyglow.color("blue",  100)
	sleep(0.1)

#	pyglow.color("white",  10)
#       sleep(1) 

# 	pyglow.color("white",   0)
#       sleep(0.1) 
        pyglow.color("blue",    0)
        sleep(0.1)
        pyglow.color("green",   0)
        sleep(0.1)
        pyglow.color("yellow",  0)
        sleep(0.1)
        pyglow.color("orange",   0)
        sleep(0.1)
        pyglow.color("red",   0)
        sleep(0.1)
	
	count = count + 1
