from PyGlow import PyGlow
from time import sleep

pyglow = PyGlow()

pyglow.all(0)

while True:
# blue > purple > red
	pyglow.color("blue", 100)
	pyglow.color("red",  0)
	sleep(0.1)
	pyglow.color("red", 10)
	pyglow.color("blue", 90)
	sleep(0.1)
	pyglow.color("red", 20)
	pyglow.color("blue", 80)
	sleep(0.1)
	pyglow.color("red", 30)
	pyglow.color("blue", 70)
	sleep(0.1)
	pyglow.color("red", 40)
	pyglow.color("blue", 60)
	sleep(0.1)
	pyglow.color("red", 50)
	pyglow.color("blue", 50)
	sleep(0.1)
	pyglow.color("red", 60)
	pyglow.color("blue", 40)
   	sleep(0.1)
	pyglow.color("red", 70)
	pyglow.color("blue", 30)
	sleep(0.1)
	pyglow.color("blue", 80)
	pyglow.color("blue", 20)
	sleep(0.1)
	pyglow.color("red", 90)
        pyglow.color("blue", 10)
        sleep(0.1)
	pyglow.color("red", 100)
        pyglow.color("blue", 0)
        sleep(0.1)

# red > orange > yellow
	pyglow.color("red", 100)
        pyglow.color("yellow", 0)
        sleep(0.1)
	pyglow.color("red", 90)
        pyglow.color("yellow", 10)
        sleep(0.1)
	pyglow.color("red", 80)
        pyglow.color("yellow", 20)
        sleep(0.1)
	pyglow.color("red", 70)
        pyglow.color("yellow", 30)
        sleep(0.1)
	pyglow.color("red", 60)
        pyglow.color("yellow", 40)
        sleep(0.1)
	pyglow.color("red", 50)
        pyglow.color("yellow", 50)
        sleep(0.1)
	pyglow.color("red", 40)
        pyglow.color("yellow", 60)
        sleep(0.1)
	pyglow.color("red", 30)
        pyglow.color("yellow", 70)
        sleep(0.1)
	pyglow.color("red", 20)
        pyglow.color("yellow", 80)
        sleep(0.1)
	pyglow.color("red", 10)
        pyglow.color("yellow", 90)
        sleep(0.1)
	pyglow.color("red", 0)
        pyglow.color("yellow", 100)
        sleep(0.1)

# yellow > green > blue
	pyglow.color("yellow",100)
        pyglow.color("blue", 0)
        sleep(0.1)
	pyglow.color("yellow", 90)
        pyglow.color("blue", 10)
        sleep(0.1)
	pyglow.color("yellow", 80)
        pyglow.color("blue", 20)
        sleep(0.1)
	pyglow.color("yellow", 70)
        pyglow.color("blue", 30)
        sleep(0.1)
	pyglow.color("yellow", 60)
        pyglow.color("blue", 40)
        sleep(0.1)
	pyglow.color("yellow", 50)
        pyglow.color("blue", 50)
        sleep(0.1)
	pyglow.color("yellow", 40)
        pyglow.color("blue", 60)
        sleep(0.1)
	pyglow.color("yellow", 30)
        pyglow.color("blue", 70)
        sleep(0.1)
	pyglow.color("yellow", 20)
        pyglow.color("blue", 80)
        sleep(0.1)
	pyglow.color("yellow", 10)
        pyglow.color("blue", 90)
        sleep(0.1)
	pyglow.color("yellow", 0)
        pyglow.color("blue",100)
        sleep(0.1)

pyglow.update_leds()
